### ISSUE TITLE
Type points 

### ISSUE THREAD

**Issue by ghost** [nolanlawson/KeepScore#91]
Great app, but it would be great, if it is possible to type new points, and then click add. For games like canasta is it really stupid to klick on +10 and so on, because you will get points over 1000.

**Comment by SomeNameDee** [comment]
You can. You can long press on the plus or minus buttons to add or subtract a given number of points. You can also go into the options to customize what quantities the +10 buttons add.

**Comment by sheindel** [comment]
@M0pf mind closing this issue since the functionality already exists? Trying to clean up the issues list a bit
