### ISSUE TITLE
No way to input 0 score for a round.

### ISSUE THREAD

**Issue by SomeNameDee** [nolanlawson/KeepScore#92]
If you don't input a change of score for a player in a round, instead of skipping that round they just end up a round behind from now on. In other words, the round breakdown is always the same as the player breakdown.

**Comment by daguej** [comment]
You can -- hold down <kbd>+</kbd> and tap OK to add a zero round.

**Comment by mikkosaarinen** [comment]
You can also hold down the section showing your scores thus far and select 'add zero' from the pop up.

**Comment by sheindel** [comment]
@SomeGuyNamedDavid mind closing this issue as it's been answered? I'm hoping to see this app get some more love and start cleaning up some issues

**Comment by SomeNameDee** [comment]
No problem, glad the app's still seeing activity.
